### ISSUE TITLE
NO HOURS IN exprToNumeric

### ISSUE THREAD

**Issue by parljohn** [yalesov/php-cron-expr-parser#2]
Not sure why this hasn't been run into yet, but there is no check for the hours between 13-23, only days and months, so if you try to use hours past 12 it breaks.  Please fix.  Thanks. I added this for now so it will work:
            'jan'   => 1,
            'feb'   => 2,
            'mar'   => 3,
            'apr'   => 4,
            'may'   => 5,
            'jun'   => 6,
            'jul'   => 7,
            'aug'   => 8,
            'sep'   => 9,
            'oct'   => 10,
            'nov'   => 11,
            'dec'   => 12,
            '13' => 13,
            '14' => 14,
            '15' => 15,
            '16' => 16,
            '17' => 17,
            '17' => 17,
            '18' => 18,
            '19' => 19,
            '20' => 20,
            '21' => 21,
            '22' => 22,
            '23' => 23,

**Comment by yalesov** [comment]
Fixed by @BnitoBzh in 1975db0
